tfjob:
  name: tfjob-image-training
  
container:
  image: briaracreu.azurecr.io/chzbrgr71/image-retrain
  imageTag: 1.8-gpu
  pvcName: azure-files

training:
  randomcrop: 5
  randomscale: 5
  randombrightness: 5
  learningrate: 0.01
  trainingbatchsize: 100 
